proc cleanFrontPage { } {
	grid forget .main.right.mamDBTitle 
	grid forget .main.right.searchBox 
	grid forget .main.right.searchWhat
	grid forget .main.right.go 
	grid forget .main.right.newLbl
	grid forget .main.right.deleteLbl
	grid forget .main.right.printLbl
	grid forget .main.right.newStudentPayment
	grid forget .main.right.deleteStudentPayment
	grid forget .main.right.printRegister 
	grid forget .main.right.newStudent 
	grid forget .main.right.deleteStudent 
	grid forget .main.right.printInterviewForm
	grid forget .main.right.newPayment 
	grid forget .main.right.deletePayment 
}
proc cleanSection1 { } {
	grid forget .main.right.serviceContract 
	grid forget .main.right.scSurnameLbl 
	grid forget .main.right.scSurnameEnt
	grid forget .main.right.scFirstnameLbl 
	grid forget .main.right.scFirstnameEnt
	grid forget .main.right.scTitleLbl
	grid forget .main.right.scTitleEnt
	grid forget .main.right.scDOBLbl 
	grid forget .main.right.scDOBEnt
	grid forget .main.right.scAddressLbl
	grid forget .main.right.scAddress1Ent
	grid forget .main.right.scAddress2Ent
	grid forget .main.right.scAddress3Ent
	grid forget .main.right.scAddress4Ent
	grid forget .main.right.scPostcodeLbl
	grid forget .main.right.scPostcodeEnt
	grid forget .main.right.scHomePhoneLbl
	grid forget .main.right.scHomePhoneEnt
	grid forget .main.right.scMobilePhoneLbl 
	grid forget .main.right.scMobilePhoneEnt
	grid forget .main.right.scWorkPhoneLbl 
	grid forget .main.right.scWorkPhoneEnt
	grid forget .main.right.scEmailLbl 
	grid forget .main.right.scEmailEnt
	grid forget .main.right.scMembershipNumLbl 
	grid forget .main.right.scMembershipNumEnt
	grid forget .main.right.advance1 
	grid forget .main.right.cancel1
}
proc cleanSection2 { } {
	grid forget .main.right.studentNameLbl
	grid forget .main.right.studentNameEnt
	grid forget .main.right.studentDOBLbl
	grid forget .main.right.studentDOBEnt
	grid forget .main.right.studentMotherNameLbl 
	grid forget .main.right.studentMotherNameEnt 
	grid forget .main.right.studentMotherOccupationLbl 
	grid forget .main.right.studentMotherOccupationEnt
	grid forget .main.right.studentFatherNameLbl 
	grid forget .main.right.studentFatherNameEnt
	grid forget .main.right.studentFatherOccupationLbl
	grid forget .main.right.studentFatherOccupationEnt
	grid forget .main.right.studentContactHomeLbl 
	grid forget .main.right.studentContactHomeEnt
	grid forget .main.right.studentContactMobileLbl 
	grid forget .main.right.studentContactMobileEnt
	grid forget .main.right.studentAddressLbl 
	grid forget .main.right.studentAddressEnt1
	grid forget .main.right.studentContactEmailLbl 
	grid forget .main.right.studentContactEmailEnt
	grid forget .main.right.studentAddressEnt2
	grid forget .main.right.studentPostcodeLbl
	grid forget .main.right.studentPostcodeEnt
	grid forget .main.right.studentAddressEnt3 
	grid forget .main.right.studentAddressEnt4
	grid forget .main.right.advance2
	grid forget .main.right.retreat2
}
proc cleanSection3 { } { 
	grid forget .main.right.mentalBenefitsLbl 
	grid forget .main.right.focus 
	grid forget .main.right.alertness
	grid forget .main.right.discipline
	grid forget .main.right.motivation
	grid forget .main.right.obediance
	grid forget .main.right.selfControl
	grid forget .main.right.selfEsteem
	grid forget .main.right.selfRespect
	grid forget .main.right.betterGrades
	grid forget .main.right.concentration
	grid forget .main.right.achieveGoals
	grid forget .main.right.manageStress
	grid forget .main.right.selfConfidence
	grid forget .main.right.respectForOthers
	grid forget .main.right.healthBenefitsLbl
	grid forget .main.right.cardiovascular 
	grid forget .main.right.muscleEndurance
	grid forget .main.right.muscularStrength
	grid forget .main.right.bodyComposition
	grid forget .main.right.skillBenefitsLbl
	grid forget .main.right.agility 
	grid forget .main.right.power
	grid forget .main.right.speed 
	grid forget .main.right.balance
	grid forget .main.right.coordination
	grid forget .main.right.reactionTime
	grid forget .main.right.physicalBenefitsLbl 
	grid forget .main.right.mobilitty 
	grid forget .main.right.exercise 
	grid forget .main.right.flexibility
	grid forget .main.right.relaxation
	grid forget .main.right.endurance
	grid forget .main.right.muscleTone 
	grid forget .main.right.contitioning
	grid forget .main.right.rapidReeflexes
	grid forget .main.right.weightControl
	grid forget .main.right.physicalBenefits
	grid forget .main.right.breathingControl
	grid forget .main.right.practicalDefenseSkills
	grid forget .main.right.advance3
	grid forget .main.right.retreat3
}
proc cleanSection4 { } {
	grid forget .main.right.howFindAcademyLbl
	grid forget .main.right.howFindAcademyEnt
	grid forget .main.right.whatMotivatedLbl
	grid forget .main.right.whatMotivatedEnt
	grid forget .main.right.isThereAnyoneChildWouldLikeToAttendWithLbl 
	grid forget .main.right.attendWithYes 
	grid forget .main.right.attendWithNo
	grid forget .main.right.attendWithWhoLbl 
	grid forget .main.right.attendWithWhoEnt
	grid forget .main.right.activitiesAlready
	grid forget .main.right.activitiesAlreadyYes
	grid forget .main.right.activitiesAlreadyNo
	grid forget .main.right.activityLbl
	grid forget .main.right.activityEnt
	grid forget .main.right.mon 
	grid forget .main.right.tue
	grid forget .main.right.wed
	grid forget .main.right.thu
	grid forget .main.right.fri
	grid forget .main.right.sat
	grid forget .main.right.sun
	grid forget .main.right.timeLbl 
	grid forget .main.right.timeEnt
	grid forget .main.right.advance4
	grid forget .main.right.retreat4
}
proc cleanSection5 { } {
	grid forget .main.right.medicalConditionsLbl 
	grid forget .main.right.medicalConditionsSubLbl
	grid forget .main.right.asthma 
	grid forget .main.right.arthritus
	grid forget .main.right.diabetes
	grid forget .main.right.kneeProblems
	grid forget .main.right.backProblems
	grid forget .main.right.heartConditions
	grid forget .main.right.highBloodPressure
	grid forget .main.right.alergicReactionLbl
	grid forget .main.right.alergicReactionEnt
	grid forget .main.right.physicalLimitationsLbl
	grid forget .main.right.physicalLimitationsEnt
	grid forget .main.right.specialMedicationLbl 
	grid forget .main.right.specialMedicationEnt
	grid forget .main.right.advance5
	grid forget .main.right.retreat5
}
proc cleanSection6 { } { 
	grid forget .main.right.question5 
	grid forget .main.right.question5Y 
	grid forget .main.right.question5N 
	grid forget .main.right.question6 
	grid forget .main.right.question6Y 
	grid forget .main.right.question6N 
	grid forget .main.right.question6NoAddendum 
	grid forget .main.right.question6LikesLbl 
	grid forget .main.right.question6LikesEnt 
	grid forget .main.right.question6DislikesLbl 
	grid forget .main.right.question6DislikesEnt 
	grid forget .main.right.question7 
	grid forget .main.right.question7ntl 
	grid forget .main.right.question7fm 
	grid forget .main.right.question7o1y 
	grid forget .main.right.question8Lbl 
	grid forget .main.right.question8Ent 
	grid forget .main.right.question9Lbl 
	grid forget .main.right.question9Ent 
	grid forget .main.right.question10Lbl 
	grid forget .main.right.question10ALbl 
	grid forget .main.right.question10AEnt
	grid forget .main.right.question10BLbl 
	grid forget .main.right.question10BLbl 
	grid forget .main.right.question10CEnt 
	grid forget .main.right.question10CEnt 
	grid forget .main.right.question11Lbl 
	grid forget .main.right.question11Ent 
	grid forget .main.right.question12Lbl 
	grid forget .main.right.question12Y 
	grid forget .main.right.question12N 
	grid forget .main.right.question13Lbl 
	grid forget .main.right.question13Y 
	grid forget .main.right.question13N 
	grid forget .main.right.question14Lbl 
	grid forget .main.right.question14Y 
	grid forget .main.right.question14N 
	grid forget .main.right.question14Ent 
	grid forget .main.right.question15Lbl 
	grid forget .main.right.question15Y 
	grid forget .main.right.question15N 
	grid forget .main.right.question16Lbl 
	grid forget .main.right.question16NLbl 
	grid forget .main.right.question16NEnt 
	grid forget .main.right.question16CLbl 
	grid forget .main.right.question16CEnt 
	grid forget .main.right.submit5
}
